import { RelatedEntity } from '@/database/entities/notification.entity';
import { EntityManager } from 'typeorm';

export enum NotificationType {
  // Subscription
  SUBSCRIPTION_RENEWAL = 'SUBSCRIPTION_RENEWAL',
  SUBSCRIPTION_EXPIRATION = 'SUBSCRIPTION_EXPIRATION',
  SUBSCRIPTION_CONFIRMED = 'SUBSCRIPTION_CONFIRMED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_EXPIRATION_WARNING = 'SUBSCRIPTION_EXPIRATION_WARNING',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',

  PROMO_CODE_EXPIRY = 'PROMO_CODE_EXPIRY',

  // Payment
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILURE = 'PAYMENT_FAILURE',
  //   INVOICE_READY = 'INVOICE_READY',
  //   REFUND_PROCESSED = 'REFUND_PROCESSED',
  PAYMENT_FOR_OTHERS_REQUEST = 'PAYMENT_FOR_OTHERS_REQUEST',
  PAYMENT_FOR_OTHERS_REJECTED = 'PAYMENT_FOR_OTHERS_REJECTED',
  PAYMENT_FOR_OTHERS_FAILED = 'PAYMENT_FOR_OTHERS_FAILED',
  PAYMENT_FOR_OTHERS_SUCCESS = 'PAYMENT_FOR_OTHERS_SUCCESS',

  //order
  NEW_ORDER = 'NEW_ORDER',
  ORDER_REJECTED = 'ORDER_REJECTED',
  ORDER_CANCELED = 'ORDER_CANCELED',
  ORDER_REOPENED = 'ORDER_REOPENED',
  ORDER_ACCEPTED = 'ORDER_ACCEPTED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_RETURNED = 'ORDER_RETURNED',
  ORDER_PICKED_UP = 'ORDER_PICKED_UP',
  ORDER_PREPARING = 'ORDER_PREPARING',
  NEW_SERVICE_REQUEST = 'NEW_SERVICE_REQUEST',
  SERVICE_REQUEST_UPDATE = 'SERVICE_REQUEST_UPDATE',

  // Offers
  NEW_OFFER = 'NEW_OFFER',
  PERSONALIZED_OFFER = 'PERSONALIZED_OFFER',
  OFFER_EXPIRY_REMINDER = 'OFFER_EXPIRY_REMINDER',
  SPECIAL_OFFER = 'SPECIAL_OFFER',

  // Service Notifications
  //   SERVICE_BOOKED = 'SERVICE_BOOKED',
  //   SERVICE_PAYMENT_REMINDER = 'SERVICE_PAYMENT_REMINDER',
  SERVICE_AVAILABILITY = 'SERVICE_AVAILABILITY',
  NEW_ITEM_AVAILABLE = 'NEW_ITEM_AVAILABLE',
  //   SERVICE_RESCHEDULED = 'SERVICE_RESCHEDULED',

  // Loyalty and Points
  POINTS_EARNED = 'POINTS_EARNED',
  POINTS_REDEEMED = 'POINTS_REDEEMED',
  POINTS_EXPIRY_WARNING = 'POINTS_EXPIRY_WARNING',
  POINTS_MANUALLY_ADDED = 'POINTS_MANUALLY_ADDED',
  POINTS_EXPIRATION_WARNING = 'POINTS_EXPIRATION_WARNING',
  POINTS_EXPIRED = 'POINTS_EXPIRED',

  // Referral and Invitation Notifications
  // REFERRAL_SUCCESSFUL = 'REFERRAL_SUCCESSFUL',
  REFERRAL_REWARD = 'REFERRAL_REWARD',

  // Provider and Service Updates
  PROVIDER_NEW = 'PROVIDER_NEW',
  BRANCH_NEW = 'BRANCH_NEW',

  // Balance and Account Notifications
  BALANCE_UPDATED = 'BALANCE_UPDATED',
  //   LOW_BALANCE_WARNING = 'LOW_BALANCE_WARNING',
  ACCOUNT_VERIFIED = 'ACCOUNT_VERIFIED',
  ACCOUNT_VERIFICATION_FAILED = 'ACCOUNT_VERIFICATION_FAILED',

  // Family Member Notifications
  // FAMILY_MEMBER_ADDED = 'FAMILY_MEMBER_ADDED',
  // FAMILY_MEMBER_REMOVED = 'FAMILY_MEMBER_REMOVED',
  // FAMILY_MEMBER_SERVICE_UPDATE = 'FAMILY_MEMBER_SERVICE_UPDATE',
  // FAMILY_MEMBER_PROFILE_UPDATED = 'FAMILY_MEMBER_PROFILE_UPDATED',

  // Security and Account Notifications
  NEW_DEVICE_LOGIN = 'NEW_DEVICE_LOGIN',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_CHANGE_FAILED = 'PASSWORD_CHANGE_FAILED',
  //   ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  //   OTP_RECEIVED = 'OTP_RECEIVED',

  // Custom Ads and Promotions
  //   AD_RECOMMENDATION = 'AD_RECOMMENDATION',
  //   NEW_PRODUCT_AD = 'NEW_PRODUCT_AD',

  // App Updates
  FEATURE_ANNOUNCEMENT = 'FEATURE_ANNOUNCEMENT',
  APP_UPDATE_AVAILABLE = 'APP_UPDATE_AVAILABLE',
  MAINTENANCE_NOTIFICATION = 'MAINTENANCE_NOTIFICATION',

  // General Announcements
  SURVEY_REQUEST = 'SURVEY_REQUEST',

  // SUPPORT
  NEW_SUPPORT_TICKET = 'NEW_SUPPORT_TICKET',
  SUPPORT_TICKET_ESCALATED = 'SUPPORT_TICKET_ESCALATED',
  SUPPORT_TICKET_RESOLVED = 'SUPPORT_TICKET_RESOLVED',
  SUPPORT_TICKET_MESSAGE = 'SUPPORT_TICKET_MESSAGE',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  MAX = 'MAX',
}

export enum SystemNotificationType {
  NEW_ORDER = 'NEW_ORDER',
  CANCELED = 'CANCELED',
  ORDER_REJECTED = 'ORDER_REJECTED',
  ORDER_CANCELED = 'ORDER_CANCELED',
  ORDER_REOPENED = 'ORDER_REOPENED',
  NEW_SERVICE_REQUEST = 'NEW_SERVICE_REQUEST',
  NEW_SUPPORT_TICKET = 'NEW_SUPPORT_TICKET',
  NEW_ESCALATED_SUPPORT_TICKET = 'NEW_ESCALATED_SUPPORT_TICKET',
}

export enum RelatedEntityType {
  ORDER = 'ORDER',
  SUBSCRIPTION = 'SUBSCRIPTION',
  LOYALTY_POINTS = 'LOYALTY_POINTS',
  TICKET = 'TICKET',
  SERVICE_REQUEST = 'SERVICE_REQUEST',
}

export interface AppNotificationData {
  recipientId: string;
  relatedEntity: RelatedEntity;
  type: NotificationType;
  manager?: EntityManager;
  title?: string;
  message?: string;
}
